---
name: Chip Effect Repair
about: Request a chip's effect be repaired
title: 'Chip [CHIP_ID] Effect Repair'
labels: effect
projects: ["SitekickRemastered/3"]
---

**Chip ID**
Please list the affected chip's ID.  Please only post one chip per issue.

**Description**
What's wrong with it?

**Screenshots**
If applicable, post a picture of the chip.

**Additional information**
Add any other information here.
